version: '3'

services:
  bot:
    build: ./bot
    environment:
      - TOKEN=${TOKEN}
      - BOT_TOKEN=${TOKEN}
      - RM_HOST=${RM_HOST}
      - RM_USER=${RM_USER}
      - RM_PORT=${RM_PORT}
      - RM_PASSWORD=${RM_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      - db

  db:
    build:
      context: ./db
      args:
        - RM_PORT=${RM_PORT}
        - RM_USER=${RM_USER}
        - RM_PASSWORD=${RM_PASSWORD}
        - DB_USER=${DB_USER}
        - DB_REPL_USER=${DB_REPL_USER}
        - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
    environment:
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  db_repl:
    build:
      context: ./db_repl
      args:
        - MDB_HOST=${DB_HOST}
        - MREPL_USER=${DB_REPL_USER}
        - MDB_PORT=${DB_PORT}
    environment:
      - PGPASSWORD=${DB_REPL_PASSWORD}
      - POSTGRES_USER=${DB_REPL_USER}
      - POSTGRES_PASSWORD=${DB_REPL-PASSWORD}
    depends_on:
      - db
